const heading=document.getElementById('head')
heading.textContent='Fruit World'
heading.style.color='orange'
const div=document.getElementById('header')
div.style.backgroundColor="green"
div.style.border='solid'
div.style.borderColor='orange'
const subheading=document.getElementById('subhead')
subheading.style.color='green'
const div2=document.getElementById('thanks')
div2.style.color='blue'
div2.style.backgroundColor='skyblue'